# nginx.conf

server {
    listen 80;
    
    # 1. Express API Routing (/api)
    location /api/ {
        proxy_pass http://backend:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Next.js Dynamic App Routing (/app)
    location /app/ {
        proxy_pass http://next_frontend:3000;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Next.js system files (required for styling and hydration)
    location /_next/ {
        proxy_pass http://next_frontend:3000/_next/;
    }

    # 3. Jekyll Static Site (The Fallback)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri.html $uri/index.html $uri/ =404;
        }
        
        error_page 404 /404.html;
}