name: GH Pages Production Deploy

on:
  push:
    branches: [ master ]

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    # caches and runs bundle automatically - see
    # https://github.com/ruby/setup-ruby#caching-bundle-install-automatically
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    # Standard usage
    - uses:  helaili/jekyll-action@2.0.3
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
